# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Captain's Log
description: >
  Sundial's No Man's Sky Captain's Log
baseurl: ""
url: "http://captainslog.flyingtuttys.com" # the base hostname & protocol for your site
twitter_username: sundial_o7
gems: [jekyll-paginate]
paginate: 5

# Build settings
markdown: kramdown
